[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
markers = [
    "evaluators: Evaluators classes",
    "models: Models",
    "dataset: Dataset loaders",
    "preprocessing: Preprocessing"
]