[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
markers = [
    "graph_level: Graph level",
    "all_dependencies: All module dependencies",
    "min_dependencies: Min module dependencies"
]
